apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
    name: hw-demo-aks-westus-agentpool
spec:
    type: 0
    resourceID: /subscriptions/6152dde1-b5ce-41f3-9a19-ff98dff9bb63/resourcegroups/MC_hw-demo-rg-westus-aks_hw-demo-aks-westus_westus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/hw-demo-aks-westus-agentpool
    clientID: 13fd88b1-c5fb-4cce-9432-a607f0743452

---

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: hw-demo-aks-westus-agentpool-binding
spec:
    azureIdentity: hw-demo-aks-westus-agentpool
    selector: aks-demo-app-kv