apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv-secrets-demo
  namespace: primary
spec:
  provider: azure
  secretObjects:
   - data:
       - key: myOtherNewSecret
         objectName: myOtherNewSecret
       - key: myNewSecret
         objectName: myNewSecret
       - key: myNestedNewSecret
         objectName: myNestedNewSecret
       - key: myNestedOtherNewSecret
         objectName: myNestedOtherNewSecret
     secretName: appsettings
     type: Opaque
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "hwkv1fordemo"
    resourceGroup: "hw-west-rg-kv"
    cloudName: "AzurePublicCloud"
    subscriptionId: "722daa54-db9c-4486-81e8-fe8e9c3a8773"
    tenantId: "cee5d4e9-42e5-48c2-8a03-3406fd5b9242"
    objects: | 
      array:
        - |
          objectName: myOtherNewSecret
          objectType: secret
          objectVersion: ""  
        - |
          objectName: myNewSecret
          objectType: secret
          objectVersion: ""
        - |
          objectName: myNestedNewSecret
          objectType: secret
          objectVersion: ""
        - |
          objectName: myNestedOtherNewSecret
          objectType: secret
          objectVersion: ""