apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-demo-app-kv
  namespace: primary
spec:
  provider: azure
  secretObjects:
   - data:
       - key: myOtherNewSecret
         objectName: myOtherNewSecret
       - key: myNewSecret
         objectName: myNewSecret
       - key: myNestedNewSecret
         objectName: myNestedNewSecret
       - key: myNestedOtherNewSecret
         objectName: myNestedOtherNewSecret
     secretName: appsettings
     type: Opaque
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "keyvault85a8"
    resourceGroup: "hw-demo-west-rg-kv"
    cloudName: "AzurePublicCloud"
    subscriptionId: "6152dde1-b5ce-41f3-9a19-ff98dff9bb633"
    tenantId: "cee5d4e9-42e5-48c2-8a03-3406fd5b9242"
    objects: | 
      array:
        - |
          objectName: myOtherNewSecret
          objectType: secret
          objectVersion: ""  
        - |
          objectName: myNewSecret
          objectType: secret
          objectVersion: ""
        - |
          objectName: myNestedNewSecret
          objectType: secret
          objectVersion: ""
        - |
          objectName: myNestedOtherNewSecret
          objectType: secret
          objectVersion: ""