apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: primary
  name: aks-demo-app
  labels:
    app: aks-demo-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  selector:
    matchLabels:
      app: aks-demo-app
  template:
    metadata:
      labels:
        app: aks-demo-app
        aadpodidbinding: aks-demo-app-kv    
    spec:      
      containers:
        - name: aks-demo-app          
          image: "hwdemohwacr.azurecr.io/aks_demo_app:v1"
          resources:
            limits:
              cpu: 300m # How much CPU should we preallocate for each instance of this container, in millicpus
              memory: 1024Mi # How much RAM should we preallocate for each instance of this container
            requests:
              cpu: 200m # How much CPU should we allow for requests before triggering a new container, in millicpus
              memory: 256Mi # How much RAM should we allow for requests before triggering a new container, in millicpus
          ports:
          - containerPort: 80
          volumeMounts:
          - name: appsettings
            mountPath: "/mnt/appsettings"
            readOnly: true    
          env:
          - name: myOtherNewSecret
            valueFrom:
              secretKeyRef:
                name: appsettings
                key: myOtherNewSecret
          - name: myNewSecret
            valueFrom:
              secretKeyRef:
                name: appsettings
                key: myNewSecret
          - name: MySecrets__myOtherNewSecret  #__ lets us create nested app settings in .net
            valueFrom:
              secretKeyRef:
                name: appsettings
                key: myNestedOtherNewSecret
          - name: MySecrets__myNewSecret
            valueFrom:
              secretKeyRef:
                name: appsettings
                key: myNestedNewSecret
          - name: myNonSecretAppSetting
            value: "I'm not a secret, just a setting"
      volumes:
        - name: appsettings
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aks-demo-app-kv

---

apiVersion: v1
kind: Service
metadata:
  name: aks-demo-app
  namespace: primary
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-demo-app

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: aks-demo-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aks-demo-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi
  # Uncomment these lines if you create the custom packets_per_second metric and
  # configure your app to export the metric.
  # - type: Pods
  #   pods:
  #     metric:
  #       name: packets_per_second
  #     target:
  #       type: AverageValue
  #       averageValue: 100