apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-tls
  namespace: nginx
spec:
  provider: azure
  secretObjects:                                                   
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: ingresscert
      key: tls.key
    - objectName: ingresscert
      key: tls.crt
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "keyvault85a8"
    resourceGroup: "hw-demo-west-rg-kv"
    cloudName: "AzurePublicCloud"
    subscriptionId: "6152dde1-b5ce-41f3-9a19-ff98dff9bb63"
    tenantId: "cee5d4e9-42e5-48c2-8a03-3406fd5b9242"
    objects: |
      array:
        - |
          objectName: ingresscert
          objectType: secret
